# Generated by Django 5.2.13 on 2026-04-13 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_coursecompletion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('title', models.CharField(help_text='Ej: PhD en Astrofísica', max_length=255, verbose_name='Título académico')),
                ('bio', models.TextField(verbose_name='Biografía profesional')),
                ('avatar_url', models.CharField(blank=True, help_text='Ruta a la imagen del profesor (estética galáctica).', max_length=500, verbose_name='URL del Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subjects', models.ManyToManyField(related_name='professors', to='courses.category', verbose_name='Asignaturas que imparte')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
