# Generated by Django 5.2.13 on 2026-04-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Si está marcado, el profesor aparecerá en la landing page pública para los padres.', verbose_name='Destacado en Home'),
        ),
    ]
