# Generated by Django 5.2.13 on 2026-04-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_professor_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cv_json',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena formación, experiencia y habilidades en formato JSON.', verbose_name='Datos del Currículum'),
        ),
    ]
