# Generated by Django 5.2.13 on 2026-04-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursecompletion_options_and_more'),
        ('teachers', '0003_professor_cv_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje / Duda')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta del Profesor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ANSWERED', 'Respondida')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('meeting_link', models.CharField(blank=True, max_length=500, verbose_name='Enlace de Videollamada (Jitsi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='courses.course', verbose_name='Curso relacionado')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='teachers.professor', verbose_name='Profesor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-created_at'],
            },
        ),
    ]
