# Generated by Django 5.2.13 on 2026-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_live_call',
            field=models.BooleanField(default=False, verbose_name='Videollamada en Curso'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_CALL', 'En Videollamada'), ('ANSWERED', 'Resuelta')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
    ]
