# Generated by Django 6.0.3 on 2026-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_consultation_is_live_call_alter_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Leído por el alumno'),
        ),
    ]
