# Generated by Django 6.0.3 on 2026-03-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nivel de Conocimiento (Tema)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden Sugerido')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_levels', to='courses.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Nivel de Conocimiento',
                'verbose_name_plural': 'Niveles de Conocimiento',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('knowledge_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.knowledgelevel', verbose_name='Nivel de Conocimiento')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Lección')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido Teórico')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del Vídeo')),
                ('is_premium', models.BooleanField(default=True, verbose_name='Requiere Nivel 2 o 3')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta / Enunciado')),
                ('options', models.JSONField(help_text="Formato: ['Opcion A', 'Opcion B']", verbose_name='Opciones (JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Respuesta Correcta')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
    ]
