# Generated by Django 5.2.13 on 2026-04-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_xp_reward_coursecompletion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecompletion',
            options={'verbose_name': 'Completitud de Curso', 'verbose_name_plural': 'Completitudes de Curso'},
        ),
        migrations.AlterModelOptions(
            name='knowledgelevel',
            options={'ordering': ['order'], 'verbose_name': 'Nivel de Conocimiento', 'verbose_name_plural': 'Niveles de Conocimiento'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Lección', 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.RemoveField(
            model_name='knowledgelevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Posición en el curso'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la asignatura'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='knowledge_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.knowledgelevel'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Título del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='xp_reward',
            field=models.IntegerField(default=300, verbose_name='Puntos XP que da al completar'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de completitud'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_answer',
            field=models.CharField(help_text='Debe coincidir exactamente con una de las opciones del campo "options".', max_length=500, verbose_name='Respuesta correcta'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='options',
            field=models.JSONField(help_text='Lista de opciones en formato JSON. Ejemplo: ["A", "B", "C", "D"]', verbose_name='Opciones de respuesta'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='knowledgelevel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_levels', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='knowledgelevel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del nivel'),
        ),
        migrations.AlterField(
            model_name='knowledgelevel',
            name='order',
            field=models.IntegerField(default=1, help_text='Se compara con el nivel RPG del alumno. Si es mayor, el nivel está bloqueado.', verbose_name='Orden / Dificultad'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, default='', help_text='El texto de teoría que verá el alumno en la pestaña "Manual Teórico".', verbose_name='Contenido teórico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Título de la lección'),
        ),
    ]
