# Generated by Django 6.0.3 on 2026-04-20 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursecompletion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_by_users', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Curso',
                'verbose_name_plural': 'Progresos de Curso',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
