apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genioacademy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Autocertificación automática con Let's Encrypt / Cert-Manager si está habilitado
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Fuerza redirección HTTPS
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - cristina2daw.es
        - www.cristina2daw.es
        - api.cristina2daw.es
      secretName: genioacademy-tls # Secret conteniendo el certificado SSL/TLS de producción
  rules:
    # ── DOMINIO PRINCIPAL (FRONTEND) ──
    - host: cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: www.cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

    # ── SUBDOMINIO API (BACKEND) ──
    - host: api.cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
