apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genioacademy-ingress
  annotations:
    # K3s usa Traefik como ingress controller por defecto, no nginx
    # Usamos ingressClassName en spec en vez de la anotación deprecada
spec:
  # Traefik es el ingress controller que viene incluido en K3s
  ingressClassName: traefik
  rules:
    # ── DOMINIO PRINCIPAL (FRONTEND) ──
    - host: cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
    - host: www.cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

    # ── SUBDOMINIO API (BACKEND) ──
    - host: api.cristina2daw.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
