# Generated by Django 5.2.12 on 2026-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_student_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Nivel Global de Alumno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos de Experiencia (XP)'),
        ),
    ]
