# Generated by Django 5.2.12 on 2026-03-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_current_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_avatar',
            field=models.CharField(default='buho1', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_student_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
    ]
