# Generated by Django 5.2.13 on 2026-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_selected_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_student_level',
            field=models.IntegerField(default=1, help_text='Sube automáticamente al acumular XP. Desbloquea niveles de dificultad.', verbose_name='Nivel RPG del Alumno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='Puntos de Experiencia (XP)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='selected_avatar',
            field=models.CharField(default='buho1', help_text='Identificador del búho seleccionado. Ejemplo: "buho1", "buho2".', max_length=50, verbose_name='Avatar Activo (Búho)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_level',
            field=models.IntegerField(choices=[(1, 'Órbita Base — Solo teoría y quiz básico (6,99€/mes)'), (2, 'Velocidad Luz — + IA Búho Genio 24/7 (12,99€/mes)'), (3, 'Agujero de Gusano — + Tutorías con profesor real (24,99€/mes)')], default=1, help_text='Controla qué funciones ve el alumno en la plataforma.', verbose_name='Plan de Suscripción'),
        ),
    ]
