# Generated by Django 5.2.13 on 2026-04-09 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_current_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_life_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Reloj maestro para regeneración pasiva (+1 vida cada 2 horas).', verbose_name='Última actualización de vidas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='lives_count',
            field=models.IntegerField(default=3, help_text='Máximo 3. Se pierde una vida al fallar un simulador.', verbose_name='Vidas (Planetas)'),
        ),
        migrations.CreateModel(
            name='MinigameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minigame_id', models.CharField(help_text='Ejemplo: "parejas", "calculo", "ahorcado".', max_length=50, verbose_name='Identificador del Minijuego')),
                ('last_played_at', models.DateTimeField(auto_now=True, verbose_name='Última partida jugada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'minigame_id')},
            },
        ),
    ]
