# Generated by Django 5.2.13 on 2026-04-09 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_life_update_customuser_lives_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minigamelog',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_life_update',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_life_lost_at',
            field=models.DateTimeField(blank=True, help_text='Punto de partida del reloj de regeneración de 2 horas.', null=True, verbose_name='Momento de pérdida de la última vida'),
        ),
        migrations.AddField(
            model_name='minigamelog',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Jugado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lives_count',
            field=models.IntegerField(default=3, help_text='Máximo 3. Se pierden al fallar una evaluación y se regeneran con el tiempo.', verbose_name='Planetas (Vidas)'),
        ),
        migrations.AlterField(
            model_name='minigamelog',
            name='minigame_id',
            field=models.CharField(max_length=50, verbose_name='ID del minijuego'),
        ),
        migrations.AlterField(
            model_name='minigamelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_logs', to=settings.AUTH_USER_MODEL, verbose_name='Alumno'),
        ),
        migrations.RemoveField(
            model_name='minigamelog',
            name='last_played_at',
        ),
    ]
