# Generated by Django 5.2.13 on 2026-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_minigamelog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_streak_update',
            field=models.DateField(blank=True, help_text='Fecha en la que se incrementó la racha por última vez.', null=True, verbose_name='Última actualización de racha'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_count',
            field=models.IntegerField(default=0, help_text='Días consecutivos que el alumno se ha conectado.', verbose_name='Racha de días'),
        ),
    ]
